%Sinusoidal Sequence
N=100;
n=0:1:N-1;
a=input('Enter the desired length of the sequence =');
x1=cos(pi*n);
subplot(3,2,1),stem(n,x1);
xlabel('n'),ylabel('x1(n)');
title('Sinusoidal sequence');
x2=cos(pi/2*n);
subplot(3,2,2),stem(n,x2);
xlabel('n'),ylabel('x2(n)');
title('Sinusoidal sequence');
x3=cos(pi/4*n);
subplot(3,2,3),stem(n,x3);
xlabel('n'),ylabel('x3(n)');
title('Sinusoidal sequence');
x4=cos(pi/8*n);
subplot(3,2,4),stem(n,x4);
xlabel('n'),ylabel('x4(n)');
title('Sinusoidal sequence');
N=100;
n=0:1:N-1;
x5=cos(pi/16*n);
subplot(3,2,5),stem(n,x5);
xlabel('n'),ylabel('x5(n)');
title('Sinusoidal sequence');
x6=cos(pi/32*n);
subplot(3,2,6),stem(n,x6);
xlabel('n'),ylabel('x6(n)');
title('Sinusoidal sequence');